// <auto-generated />
namespace UdfCodeFirstSample.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-rc1-20726")]
    public sealed partial class Entities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Entities));
        
        string IMigrationMetadata.Id
        {
            get { return "201307261908265_Entities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
